### ISSUE TITLE
where is Map of Pin to GPIO?

### ISSUE THREAD

**Issue by bluejazzCHN** [sipeed/MaixPy_DOC#35]

**Comment by Neutree** [comment]
https://wiki.sipeed.com/en/maix/board/

**Comment by bluejazzCHN** [comment]
it‘s not detail and some wrong, for example led-r.

**Comment by QinYUN575** [comment]
You can download the corresponding hardware schematic from https://dl.sipeed.com according to you hardware.(eg: [Maix Dock Schematic](https://dl.sipeed.com/MAIX/HDK/Maix-Dock/Maix-Dock_11.27), dl.sipeed.com->MAIX->HDK->Maix-Dock->Maix-Dock_11.27->Maix-Dock_11.27(Schematic).pdf)
Of course, if you are familiar with micropython, you can use the `>>> board_info.pin_map()` , command to query the corresponding pin map.
| Pin | Function |
|---|---|
| ... | ... |
| 12 | LED_B |
| 13 | LED_G |
| 14 | LED_R |
| ... | ... |
