### ISSUE TITLE
MaixPy IDE / can not connect anymore, after RUN SCRIPT

### ISSUE THREAD

**Issue by Belgium-47** [sipeed/MaixPy_DOC#37]
Hlo All,
experimenting with the Maix_bit GO works fine
Using MaixPy IDE / windows is working for me
After Connecting and run script, flashing the board everything works.
Now i want run new script the board wil not connect and stays running programmed script.
In IDE i can connect serial port / select board.
When i push CONNECT, Maix_Bit startsup programmed script, but stays in loop to try connection. 
How to solve this problem. ?

**Comment by Fosyan** [comment]
try re-flash the firmware
and upload your new scrips again

(that I do)

**Comment by Belgium-47** [comment]
Hlo Fosyan,
thanks for the reply. I re-flashed the firmware several times...no result.
At last : i think i Flashed the firmware wrong. When i Download the firmware to board, i flashed it to  "FLASH memory" in Kflash_Gui, instead of SRAM. 
After download to SRAM everything works fine again.
