### ISSUE TITLE
SD卡可以被MAIX GO识别、写文件，但电脑无法识别 

### ISSUE THREAD

**Issue by HFUTLCW** [sipeed/MaixPy_DOC#41]
SD卡在MAIX GO可写boot.py,但是把卡取下来用读卡器接电脑电脑却始终无法识别，可是这张卡在插上GO之前是可以识别的，拿其他卡又试了一次结果一样，请问要怎么解决？

**Comment by QinYUN575** [comment]
请根据查看文档中提供的方法解决 [Micro SD 卡读取不到](https://cn.maixpy.sipeed.com/zh/others/maixpy_faq.html#micro-sd-%E5%8D%A1%E8%AF%BB%E5%8F%96%E4%B8%8D%E5%88%B0)
