### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by AminovE99** [sipeed/MaixPy_DOC#49]
## Description of the issue
When I try to  upload this code on my maixduino I receive this Traceback in console:
```
Traceback (most recent call last):
  File "boot.py", line 97, in <module>
IndexError: list index out of range
init i2c2

[MAIXPY]: find gc3028
encrypted model
[MAIXPY]kpu: img w=320,h=240, but model w=128,h=128

Traceback (most recent call last):
  File "main.py", line 18, in <module>
ValueError: [MAIXPY]kpu: check img format err!
```

I created pull request to fix it, but I suppose it is not perfect solution (https://github.com/sipeed/MaixPy_scripts/pull/73)

**Comment by alexeiSP** [comment]
I had the same error.
Error was called when there is a face before camera and device tried to recognize it (but does not have saved faces). 
In some cases after reset device tries to search in memory recognized faced (when has no one). When search reached "Mr. 10", error is called.
