### ISSUE TITLE
文档标题错误

### ISSUE THREAD

**Issue by jiezhuo** [sipeed/MaixPy_DOC#66]
还不会PR以后再学(捂脸)
API手册-Maix-KPU里面的2.3和2.5标题重复,2.5的标题应该是 run_yolo2

**Comment by Neutree** [comment]
已经修改， https://en.maixpy.sipeed.com/maixpy/zh/api_reference/Maix/kpu.html#init_yolo2-2
会慢慢同步到maixpy.sipeed.com的
