### ISSUE TITLE
sd card not recognized?

### ISSUE THREAD

**Issue by lovettchris** [sipeed/MaixPy_DOC#9]
Using maixpy_v0.2.4_full_with_model_at_0x300000.zip I'm not seeing any micropython "sdcard" module, so "import sdcard" fails (which I saw in [your test](https://github.com/sipeed/MaixPy/blob/master/drivers/sdcard/sdcard.py))

I'm using [Samsung Evo Select 32gb](https://www.amazon.com/gp/product/B06XWN9Q99/ref=ppx_yo_dt_b_asin_title_o09_s00?ie=UTF8&psc=1) card which is class 10.  

Am I missing a step in getting this card to be recognized?

**Comment by Neutree** [comment]
It's better to create issues in MaixPy repo as you did, I'll close this one~~
